Repository TGlide/radix-svelte, pull requests merged in 2023-04, with the labels that each got.

#41 :sparkles: add toggle component
  .vscode/custom.code-snippets
  src/lib/components/Accordion/root.svelte
  src/lib/components/Toggle/index.ts
  src/lib/components/Toggle/root.svelte
  src/lib/components/index.ts
  src/lib/types.ts
  src/routes/(previews)/Accordion.svelte
  src/routes/(previews)/Collapsible.svelte
  src/routes/(previews)/Toggle.svelte
  src/routes/+page.svelte
  tsconfig.json
Labels: component

#43 Add vitests to collapsible
  .gitignore
  package.json
  playwright-ct.config.ts
  playwright.config.ts
  playwright/index.html
  playwright/index.ts
  scripts/setup-test.js
  src/lib/components/Collapsible/content.svelte
  src/lib/components/Collapsible/root.svelte
  src/lib/components/Collapsible/tests/Collapsible.pw.ts
  src/lib/components/Collapsible/tests/Collapsible.test.ts
  src/lib/components/Collapsible/tests/cmp.svelte
  src/lib/types.ts
  src/routes/(previews)/Collapsible.svelte
  tests/test.ts
  tsconfig.json
  vite.config.ts
  yarn.lock
Labels: tech debt

#51 Interactive docs
  .eslintrc.cjs
  .storybook/main.ts
  .storybook/preview.ts
  package.json
  src/lib/components/Accordion/item.svelte
  src/lib/components/Accordion/stories/Accordion.stories.ts
  src/lib/components/Accordion/stories/AccordionStyled.svelte
  src/lib/components/Collapsible/index.ts
  src/lib/components/Collapsible/stories/Collapsible.stories.ts
  src/lib/components/Collapsible/stories/CollapsibleStyled.svelte
  src/lib/helpers/object.ts
  src/routes/(previews)/Accordion/example.svelte
  src/routes/(previews)/Accordion/schema.ts
  src/routes/(previews)/Collapsible/example.svelte
  src/routes/(previews)/Collapsible/schema.ts
  src/routes/(previews)/README.md
  src/routes/(previews)/Toggle/example.svelte
  src/routes/(previews)/Toggle/schema.ts
  src/routes/(previews)/helpers.ts
  src/routes/(previews)/schemas.ts
  src/routes/+page.svelte
  src/routes/[component]/+page.svelte
  src/routes/[component]/+page.ts
  svelte.config.js
  tsconfig.json
  yarn.lock
Labels: enhancement

#53 Add checkbox component
  src/lib/components/Checkbox/index.ts
  src/lib/components/Checkbox/indicator.svelte
  src/lib/components/Checkbox/root.svelte
  src/lib/components/Checkbox/tests/Checkbox.test.ts
  src/lib/components/Checkbox/tests/CheckboxTest.svelte
  src/lib/components/index.ts
  src/routes/(previews)/Checkbox/example.svelte
  src/routes/(previews)/Checkbox/schema.ts
  src/routes/(previews)/schemas.ts
Labels: component

#54 ✨Component: accordion flourishes
  src/app.postcss
  src/lib/components/Accordion/header.svelte
  src/lib/components/Accordion/index.ts
  src/lib/components/Accordion/item.svelte
  src/lib/components/Accordion/root.svelte
  src/lib/components/Accordion/trigger.svelte
  src/lib/components/Collapsible/index.ts
  src/lib/components/Collapsible/root.svelte
  src/lib/components/Collapsible/trigger.svelte
  src/lib/components/Toggle/index.ts
  src/lib/components/Toggle/root.svelte
  src/lib/helpers/dom.ts
  src/lib/types.ts
  src/routes/(previews)/Accordion/example.svelte
  src/routes/(previews)/Accordion/schema.ts
  src/routes/(previews)/Checkbox/example.svelte
  src/routes/(previews)/Checkbox/schema.ts
  src/routes/(previews)/Collapsible/example.svelte
  src/routes/(previews)/Collapsible/schema.ts
  src/routes/(previews)/Toggle/example.svelte
  src/routes/(previews)/Toggle/schema.ts
  src/routes/(previews)/helpers.ts
  src/routes/+page.svelte
  src/routes/[component]/+page.svelte
Labels: component

#57 Add Switch primitive
  src/lib/components/Switch/index.ts
  src/lib/components/Switch/root.svelte
  src/lib/components/Switch/tests/Switch.test.ts
  src/lib/components/Switch/tests/SwitchTest.svelte
  src/lib/components/Switch/thumb.svelte
  src/lib/components/index.ts
  src/routes/(previews)/Switch/example.svelte
  src/routes/(previews)/Switch/schema.ts
  src/routes/(previews)/schemas.ts
Labels: component

#58 :art: WIP reactive context
  src/lib/components/Accordion/item.svelte
  src/lib/components/Accordion/root.svelte
  src/lib/components/Accordion/trigger.svelte
  src/lib/components/Checkbox/indicator.svelte
  src/lib/components/Checkbox/root.svelte
  src/lib/components/Collapsible/content.svelte
  src/lib/components/Collapsible/root.svelte
  src/lib/components/Collapsible/trigger.svelte
  src/lib/components/Switch/root.svelte
  src/lib/components/Switch/thumb.svelte
  src/lib/helpers/controllableState.ts
  src/lib/helpers/reactiveContext.ts
  src/routes/(previews)/Switch/example.svelte
  src/routes/(previews)/Switch/schema.ts
Labels: tech debt

#62 :sparkles: add aspect-ratio component
  src/lib/components/AspectRatio/index.ts
  src/lib/components/AspectRatio/root.svelte
  src/lib/components/AspectRatio/tests/AspectRatio.test.ts
  src/lib/components/AspectRatio/tests/AspectRatioTest.svelte
  src/lib/components/index.ts
  src/routes/(previews)/AspectRatio/example.svelte
  src/routes/(previews)/AspectRatio/schema.ts
  src/routes/(previews)/schemas.ts
  src/routes/+page.svelte
Labels: enhancement

#70 feat: progress
  src/lib/components/Progress/index.ts
  src/lib/components/Progress/indicator.svelte
  src/lib/components/Progress/root.svelte
  src/lib/components/Progress/tests/Progress.test.ts
  src/lib/components/Progress/tests/ProgressTest.svelte
  src/lib/components/index.ts
  src/routes/(previews)/Progress/example.svelte
  src/routes/(previews)/Progress/schema.ts
  src/routes/(previews)/schemas.ts
Labels: component

#80 feat(nvm): Add .nvmrc file with current LTS vertion
  .nvmrc
Labels: tech debt

#74 Add Popper component
  package.json
  pnpm-lock.yaml
  src/lib/components/Arrow/index.ts
  src/lib/components/Arrow/root.svelte
  src/lib/components/index.ts
  src/lib/internal/components/Popper/anchor.svelte
  src/lib/internal/components/Popper/arrow.svelte
  src/lib/internal/components/Popper/content.svelte
  src/lib/internal/components/Popper/index.ts
  src/lib/internal/components/Popper/root.svelte
  src/lib/internal/components/Popper/tests/Popper.test.ts
  src/lib/internal/components/Popper/tests/PopperTest.svelte
  src/lib/internal/components/Popper/utils.ts
  src/lib/internal/components/Portal/Portal.svelte
  src/lib/internal/components/index.ts
  src/lib/types.ts
  src/routes/(previews)/Popper/example.svelte
  src/routes/(previews)/Popper/schema.ts
  src/routes/(previews)/Slider/example.multiple.svelte
  src/routes/(previews)/schemas.ts
  src/routes/+page.svelte
  src/routes/[component]/+page.ts
Labels: component

#81 :sparkles: Tabs
  .vscode/custom.code-snippets
  pnpm-lock.yaml
  src/lib/components/Slider/root.svelte
  src/lib/components/Tabs/content.svelte
  src/lib/components/Tabs/index.ts
  src/lib/components/Tabs/list.svelte
  src/lib/components/Tabs/root.svelte
  src/lib/components/Tabs/tests/Tabs.test.ts
  src/lib/components/Tabs/tests/TabsTest.svelte
  src/lib/components/Tabs/trigger.svelte
  src/lib/components/index.ts
  src/lib/helpers/array.ts
  src/routes/(previews)/Tabs/example.svelte
  src/routes/(previews)/Tabs/schema.ts
  src/routes/(previews)/schemas.ts
Labels: component

#82 Release/next
  .github/workflows/publish.yml
  .github/workflows/release_package.yml
  .versionrc.cjs
  CHANGELOG.md
  RELEASES.md
  package.json
  scripts/check-git-status.sh
  scripts/release.sh
Labels: release

#89 chore(release): 0.3.1
  CHANGELOG.md
  package.json
Labels: release

#90 Release 0.3.1 into main
  CHANGELOG.md
  package.json
  src/routes/(previews)/Toggle/schema.ts
  src/routes/docs/[component]/+page.svelte
Labels: release

#91 feat: component creator script
  .vscode/custom.code-snippets
  package.json
  scripts/create-component.js
Labels: enhancement

#98 chore(release): 0.3.4
  CHANGELOG.md
  package.json
Labels: release

#99 Merge dev into main
  .vscode/custom.code-snippets
  CHANGELOG.md
  package.json
  scripts/create-component.js
  src/lib/components/Avatar/tests/Avatar.test.ts
  src/lib/components/Slider/internal/SliderHorizontal.svelte
  src/lib/components/Slider/internal/SliderVertical.svelte
  src/lib/index.ts
  src/lib/internal/helpers/index.ts
  src/lib/internal/helpers/preview.ts
  src/routes/(previews)/Accordion/schema.ts
  src/routes/(previews)/AspectRatio/example.svelte
  src/routes/(previews)/AspectRatio/schema.ts
  src/routes/(previews)/Avatar/example.svelte
  src/routes/(previews)/Avatar/schema.ts
  src/routes/(previews)/Checkbox/example.svelte
  src/routes/(previews)/Checkbox/schema.ts
  src/routes/(previews)/Collapsible/example.svelte
  src/routes/(previews)/Collapsible/schema.ts
  src/routes/(previews)/Dialog/example.svelte
  src/routes/(previews)/Dialog/schema.ts
  src/routes/(previews)/Popper/example.svelte
  src/routes/(previews)/Popper/schema.ts
  src/routes/(previews)/Progress/example.svelte
  src/routes/(previews)/Progress/schema.ts
  src/routes/(previews)/Slider/example.multiple.svelte
  src/routes/(previews)/Slider/example.svelte
  src/routes/(previews)/Slider/schema.ts
  src/routes/(previews)/Switch/example.svelte
  src/routes/(previews)/Switch/schema.ts
  src/routes/(previews)/Tabs/example.svelte
  src/routes/(previews)/Tabs/schema.ts
  src/routes/(previews)/Toggle/example.svelte
  src/routes/(previews)/Toggle/schema.ts
  src/routes/+page.svelte
  src/routes/docs/[component]/+page.svelte
  src/routes/helpers.ts
Labels: release

#101 feat: toggle group
  .eslintignore
  .prettierignore
  src/lib/components/Accordion/root.svelte
  src/lib/components/Tabs/list.svelte
  src/lib/components/Tabs/trigger.svelte
  src/lib/components/Toggle/root.svelte
  src/lib/components/ToggleGroup/index.ts
  src/lib/components/ToggleGroup/item.svelte
  src/lib/components/ToggleGroup/root.svelte
  src/lib/components/ToggleGroup/tests/ToggleGroup.test.ts
  src/lib/components/ToggleGroup/tests/ToggleGroupTest.svelte
  src/lib/components/index.ts
  src/lib/internal/helpers/array.ts
  src/routes/(previews)/Accordion/example.svelte
  src/routes/(previews)/Tabs/schema.ts
  src/routes/(previews)/ToggleGroup/example.svelte
  src/routes/(previews)/ToggleGroup/schema.ts
  src/routes/(previews)/schemas.ts
Labels: component

#104 chore(release): 0.3.5
  CHANGELOG.md
  package.json
Labels: release

#116 chore(release): 0.3.6
  CHANGELOG.md
  package.json
Labels: release

#106 Revamp and polish docs
  package.json
  pnpm-lock.yaml
  src/app.html
  src/app.postcss
  src/routes/(previews)/Checkbox/example.svelte
  src/routes/(previews)/Collapsible/example.svelte
  src/routes/(previews)/Dialog/example.svelte
  src/routes/(previews)/Toggle/example.svelte
  src/routes/(previews)/ToggleGroup/example.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/docs/[component]/+layout.svelte
  src/routes/docs/[component]/+page.svelte
  static/radix-svelte.svg
  tailwind.config.ts
Labels: documentation, enhancement

#117 Update readme
  README.md
Labels: documentation
