Repository TGlide/radix-svelte, pull requests merged in 2023-05, with the labels that each got.

#122 Increase accessibility of Toggle and update Docs
  src/lib/components/Toggle/root.svelte
  src/lib/components/ToggleGroup/root.svelte
  src/routes/(previews)/Toggle/example.svelte
  src/routes/(previews)/Toggle/schema.ts
  src/routes/(previews)/ToggleGroup/example.svelte
  src/routes/(previews)/ToggleGroup/schema.ts
Labels: enhancement

#131 feat: alert dialog
  package.json
  pnpm-lock.yaml
  src/app.html
  src/constants.ts
  src/lib/components/Accordion/root.svelte
  src/lib/components/AlertDialog/action.svelte
  src/lib/components/AlertDialog/cancel.svelte
  src/lib/components/AlertDialog/content.svelte
  src/lib/components/AlertDialog/description.svelte
  src/lib/components/AlertDialog/index.ts
  src/lib/components/AlertDialog/overlay.svelte
  src/lib/components/AlertDialog/portal.svelte
  src/lib/components/AlertDialog/root.svelte
  src/lib/components/AlertDialog/tests/AlertDialog.test.ts
  src/lib/components/AlertDialog/tests/AlertDialogTest.svelte
  src/lib/components/AlertDialog/title.svelte
  src/lib/components/AlertDialog/trigger.svelte
  src/lib/components/Dialog/close.svelte
  src/lib/components/Dialog/content.svelte
  src/lib/components/Dialog/root.svelte
  src/lib/components/Dialog/trigger.svelte
  src/lib/components/RadioGroup/root.svelte
  src/lib/components/Slider/root.svelte
  src/lib/components/Tabs/list.svelte
  src/lib/components/ToggleGroup/root.svelte
  src/lib/components/Tooltip/provider.svelte
  src/lib/components/index.ts
  src/lib/internal/actions/focusTrap.ts
  src/lib/internal/helpers/collectionContext.ts
  src/lib/internal/helpers/preview.ts
  src/routes/(previews)/AlertDialog/example.svelte
  src/routes/(previews)/AlertDialog/schema.ts
  src/routes/(previews)/Checkbox/example.svelte
  src/routes/(previews)/Dialog/example.svelte
  src/routes/(previews)/Dialog/schema.ts
  src/routes/(previews)/Select/example.svelte
  src/routes/(previews)/Toggle/example.svelte
  src/routes/(previews)/schemas.ts
  src/routes/+layout.svelte
  src/routes/+page.svelte
  src/routes/docs/[component]/+page.svelte
  src/routes/test/+page.svelte
  src/routes/test/+page.ts
  svelte.config.js
Labels: component

#141 feat: select number prop
  .changeset/unlucky-eyes-type.md
  src/lib/components/Slider/root.svelte
  src/routes/(previews)/Slider/example.svelte
  src/routes/(previews)/Slider/schema.ts
Labels: enhancement

#143 Component: HoverCard
  .changeset/moody-hornets-rescue.md
  src/lib/components/HoverCard/content.svelte
  src/lib/components/HoverCard/index.ts
  src/lib/components/HoverCard/portal.svelte
  src/lib/components/HoverCard/root.svelte
  src/lib/components/HoverCard/tests/HoverCard.test.ts
  src/lib/components/HoverCard/tests/HoverCardTest.svelte
  src/lib/components/HoverCard/trigger.svelte
  src/lib/components/index.ts
  src/lib/internal/components/Popper/anchor.svelte
  src/lib/internal/components/Popper/content.svelte
  src/routes/(previews)/HoverCard/example.svelte
  src/routes/(previews)/HoverCard/schema.ts
  src/routes/(previews)/schemas.ts
Labels: component

#150 refactor: improve reactive context
  .vscode/custom.code-snippets
  src/lib/components/Accordion/item.svelte
  src/lib/components/Accordion/root.svelte
  src/lib/components/Avatar/root.svelte
  src/lib/components/Checkbox/root.svelte
  src/lib/components/Collapsible/content.svelte
  src/lib/components/Collapsible/root.svelte
  src/lib/components/Collapsible/trigger.svelte
  src/lib/components/Dialog/root.svelte
  src/lib/components/HoverCard/root.svelte
  src/lib/components/HoverCard/trigger.svelte
  src/lib/components/Progress/root.svelte
  src/lib/components/RadioGroup/item.svelte
  src/lib/components/RadioGroup/root.svelte
  src/lib/components/Select/root.svelte
  src/lib/components/Slider/root.svelte
  src/lib/components/Switch/root.svelte
  src/lib/components/Tabs/root.svelte
  src/lib/components/ToggleGroup/root.svelte
  src/lib/internal/components/Popper/content.svelte
  src/lib/internal/components/Popper/root.svelte
  src/lib/internal/helpers/object.ts
  src/lib/internal/helpers/reactiveContext.ts
  src/lib/internal/types.ts
  src/routes/(previews)/AlertDialog/example.svelte
  src/routes/(previews)/HoverCard/example.svelte
  src/routes/(previews)/Progress/schema.ts
  src/routes/(previews)/RadioGroup/schema.ts
Labels: tech debt

#154 align `<Dialog>`docs `modal` prop default value
  .changeset/weak-penguins-marry.md
  src/lib/components/Dialog/root.svelte
Labels: bug
